### ISSUE TITLE
error during development setup

### ISSUE THREAD

**Issue by revant** [simplicy-io/eurc-eth#1]
npx truffle compile resulted in warning.

```shell
❯ npx truffle compile

Compiling your contracts...
===========================
> Compiling ./contracts/Euro.sol
> Compiling ./contracts/Migrations.sol
> Compiling @openzeppelin/contracts/GSN/Context.sol
> Compiling @openzeppelin/contracts/access/Ownable.sol
> Compiling @openzeppelin/contracts/math/SafeMath.sol
> Compiling @openzeppelin/contracts/token/ERC20/ERC20.sol
> Compiling @openzeppelin/contracts/token/ERC20/ERC20Burnable.sol
> Compiling @openzeppelin/contracts/token/ERC20/IERC20.sol
> Compilation warnings encountered:

    @openzeppelin/contracts/token/ERC20/ERC20.sol:55:5: Warning: Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
    constructor (string memory name_, string memory symbol_) public {
    ^ (Relevant source part starts here and spans across multiple lines).
,@openzeppelin/contracts/access/Ownable.sol:26:5: Warning: Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
    constructor () internal {
    ^ (Relevant source part starts here and spans across multiple lines).
,/home/revant/Projects/eurc-eth/contracts/Euro.sol:18:5: Warning: Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
    constructor (
    ^ (Relevant source part starts here and spans across multiple lines).

> Artifacts written to /home/revant/Projects/eurc-eth/build/contracts
> Compiled successfully using:
   - solc: 0.7.5+commit.eb77ed08.Emscripten.clang
```

npx truffle migrate --network development failed:

```
❯ npx truffle migrate --network development

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'development'
> Network id:      1611676665644
> Block gas limit: 6721975 (0x6691b7)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0xfaa5138ab80eb8fc6016aae5389d95e5b3a59b158b862fab190fc442af060502
   > Blocks: 0            Seconds: 0
   > contract address:    0xC733728A05E77eac01A4473f2d1fd587f67ecaf4
   > block number:        1
   > block timestamp:     1611676746
   > account:             0x720Fce7D9004b42DE3232b34f7095A081Fc8A5d7
   > balance:             99.99626074
   > gas used:            186963 (0x2da53)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00373926 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00373926 ETH

2_deploy_contracts.js
=====================

   Deploying 'Euro'
   ----------------

Error:  *** Deployment Failed ***

"Euro" -- Invalid number of parameters for "undefined". Got 0 expected 5!.

    at /home/revant/Projects/eurc-eth/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at Migration._deploy (/home/revant/Projects/eurc-eth/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/home/revant/Projects/eurc-eth/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:55:1)
    at Migration.run (/home/revant/Projects/eurc-eth/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:171:1)
    at Object.runMigrations (/home/revant/Projects/eurc-eth/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/home/revant/Projects/eurc-eth/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/home/revant/Projects/eurc-eth/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/home/revant/Projects/eurc-eth/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:269:1)
    at /home/revant/Projects/eurc-eth/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:231:1
Truffle v5.1.62 (core: 5.1.62)
Node v15.6.0
```

**Comment by iam-dev** [comment]
see commit https://github.com/simplicy-io/eurc-eth/commit/163d0833b6c9518129642ebe7bdc55f4941a3f6b
